# add kw from OpenAlex to nodes_*.csv files
This adds keywords extracted from OpenAlex to the nodes_*.csv files created by biblionet.py

In [34]:
import pandas as pd
import os
from colorama import Fore, Back, Style

In [16]:
df

                                    id                                           keywords                      sustainable_development_goals
0     https://openalex.org/W2781567654  [{'id': 'https://openalex.org/keywords/marine-...  [{'display_name': 'Life below water', 'score':...
1     https://openalex.org/W2004113883  [{'id': 'https://openalex.org/keywords/futures...  [{'display_name': 'Climate action', 'id': 'htt...
2     https://openalex.org/W2013045877  [{'id': 'https://openalex.org/keywords/traditi...  [{'display_name': 'Quality education', 'id': '...
3     https://openalex.org/W2025956066  [{'id': 'https://openalex.org/keywords/cohesio...  [{'score': 0.85, 'display_name': 'Climate acti...
4     https://openalex.org/W4245300726  [{'id': 'https://openalex.org/keywords/terrige...  [{'score': 0.78, 'id': 'https://metadata.un.or...
...                                ...                                                ...                                                ...
6003  https://openalex.org/W4281790711                                                 []  [{'id': 'https://metadata.un.org/sdg/14', 'dis...
6004  https://openalex.org/W2590599124  [{'id': 'https://openalex.org/keywords/climate...  [{'score': 0.51, 'id': 'https://metadata.un.or...
6005  https://openalex.org/W3002986681  [{'id': 'https://openalex.org/keywords/storm-s...                                                 []
6006  https://openalex.org/W2955159091  [{'id': 'https://openalex.org/keywords/capacit...  [{'id': 'https://metadata.un.org/sdg/13', 'dis...
6007  https://openalex.org/W2587571975  [{'id': 'https://openalex.org/keywords/climate...  [{'display_name': 'Climate action', 'score': 0...

[6008 rows x 3 columns]

In [19]:
id_df = df['id']
id_df

0       https://openalex.org/W2781567654
1       https://openalex.org/W2004113883
2       https://openalex.org/W2013045877
3       https://openalex.org/W2025956066
4       https://openalex.org/W4245300726
                      ...
6003    https://openalex.org/W4281790711
6004    https://openalex.org/W2590599124
6005    https://openalex.org/W3002986681
6006    https://openalex.org/W2955159091
6007    https://openalex.org/W2587571975
Name: id, Length: 6008, dtype: object

In [37]:
df = pd.read_json("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/labels/keywords_SDGs.json")
sdg_df = df[['sustainable_development_goals']]
sdg_df.iloc[0,0]
sdg_df.fillna(inplace=True, value=0)
sdg_df2 = sdg_df.map(lambda x: x[0] if len(x)>0 else None)
sdg_df3 = sdg_df2.map(lambda x: x.get('display_name') if x!=None else None)
sdg_df_merged = pd.concat([id_df,sdg_df3], axis=1)
#sdg_df_merged.fillna(inplace=True, value='None')
sdg_df_merged = sdg_df_merged.rename(columns={'id':'oa_id', 'sustainable_development_goals':'sdgs'})
sdg_df_merged.to_excel("sdgs.xlsx",index=False)
sdg_df_merged

<positron-console-cell-37>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                                 oa_id               sdgs
0     https://openalex.org/W2781567654   Life below water
1     https://openalex.org/W2004113883     Climate action
2     https://openalex.org/W2013045877  Quality education
3     https://openalex.org/W2025956066     Climate action
4     https://openalex.org/W4245300726   Life below water
...                                ...                ...
6003  https://openalex.org/W4281790711   Life below water
6004  https://openalex.org/W2590599124     Climate action
6005  https://openalex.org/W3002986681               None
6006  https://openalex.org/W2955159091     Climate action
6007  https://openalex.org/W2587571975     Climate action

[6008 rows x 2 columns]

In [36]:
#look up all files in folder that start with 'nodes_*.csv'
#list files in the directory and filter those that start with "nodes_"
# merge with sdg_df_merged on 'id'
net_files = [f for f in os.listdir("networks_copy/") if f.startswith("nodes_")]
for file in net_files:
    #read the CSV file into a DataFrame
    df = pd.read_csv(os.path.join("networks_copy", file))
    #for each in list, perform above function)

    # join df_nodes_bc with df_core_works left_on='Label', right_on='openalex_work_id', how='left'
    df = df.merge(sdg_df_merged, left_on='Label', right_on='oa_id', how='left')


    #save out each to networks overwriting the original
    output_file = os.path.join("networks_copy", file)
    df.to_csv(output_file, index=False)
    print(Fore.LIGHTGREEN_EX + f"✅ Exported file as {output_file}" + Style.RESET_ALL)

✅ Exported file as networks_copy/nodes_cc.csv
✅ Exported file as networks_copy/nodes_bc.csv
✅ Exported file as networks_copy/nodes_dc.csv
✅ Exported file as networks_copy/nodes_bc_dc.csv
✅ Exported file as networks_copy/nodes_cc_dc.csv
✅ Exported file as networks_copy/nodes_bc_cc_dc.csv
✅ Exported file as networks_copy/nodes_bc_cc.csv

In [4]:
df2 = df['keywords'].apply(pd.Series)
df2

                                                     0                                                  1   ...   10   11
0     {'id': 'https://openalex.org/keywords/marine-e...  {'id': 'https://openalex.org/keywords/biogeoch...  ...  NaN  NaN
1     {'id': 'https://openalex.org/keywords/futures-...  {'id': 'https://openalex.org/keywords/risk-soc...  ...  NaN  NaN
2     {'id': 'https://openalex.org/keywords/traditio...                                                NaN  ...  NaN  NaN
3     {'id': 'https://openalex.org/keywords/cohesion...  {'id': 'https://openalex.org/keywords/cultural...  ...  NaN  NaN
4     {'id': 'https://openalex.org/keywords/terrigen...                                                NaN  ...  NaN  NaN
...                                                 ...                                                ...  ...  ...  ...
6003                                                NaN                                                NaN  ...  NaN  NaN
6004  {'id': 'https://openalex.org/keywords/climate-...                                                NaN  ...  NaN  NaN
6005  {'id': 'https://openalex.org/keywords/storm-su...  {'id': 'https://openalex.org/keywords/coastal-...  ...  NaN  NaN
6006  {'id': 'https://openalex.org/keywords/capacity...  {'id': 'https://openalex.org/keywords/adaptive...  ...  NaN  NaN
6007  {'id': 'https://openalex.org/keywords/climate-...  {'id': 'https://openalex.org/keywords/social-j...  ...  NaN  NaN

[6008 rows x 12 columns]

In [5]:
df2.fillna(inplace=True, value=0)

df3 = df2.map(lambda x: list(x.values()) if x!=0 else 0)
df4 = df3.map(lambda x: x[1] if x != 0 and len(x)>1 else None)
df4.head(20)
df4.to_excel("keywords2.xlsx")
df4.head(20)

                           0                         1                          2                3     4   ...    7     8     9     10    11
0            Marine ecosystem           Biogeochemistry                       None             None  None  ...  None  None  None  None  None
1             Futures studies              Risk Society                       None             None  None  ...  None  None  None  None  None
2       Traditional Knowledge                      None                       None             None  None  ...  None  None  None  None  None
3        Cohesion (chemistry)         Cultural Identity                       None             None  None  ...  None  None  None  None  None
4        Terrigenous sediment                      None                       None             None  None  ...  None  None  None  None  None
5                  Resilience   Socio-ecological system  Ecological systems theory             None  None  ...  None  None  None  None  None
6           Anomaly (physics)                      None                       None             None  None  ...  None  None  None  None  None
7                     CLARITY      Environmental change                     Affect             None  None  ...  None  None  None  None  None
8                   Relevance      Earth system science     Ecological forecasting             None  None  ...  None  None  None  None  None
9                        None                      None                       None             None  None  ...  None  None  None  None  None
10                 Mainstream                      None                       None             None  None  ...  None  None  None  None  None
11               Deliberation           Social Learning                Institution             None  None  ...  None  None  None  None  None
12                   Ice core            Dome (geology)                     Coring             None  None  ...  None  None  None  None  None
13      Forcing (mathematics)                      None                       None             None  None  ...  None  None  None  None  None
14           Future sea level           Ice-sheet model        Greenland ice sheet             None  None  ...  None  None  None  None  None
15             Polycentricity      Common-pool resource                       None             None  None  ...  None  None  None  None  None
16  Maximum sustainable yield                      None                       None             None  None  ...  None  None  None  None  None
17                       Argo                    Hiatus                       None             None  None  ...  None  None  None  None  None
18                       Argo        Ocean observations                       None             None  None  ...  None  None  None  None  None
19                 Skepticism  Objectivity (philosophy)                 Moderation  Ozone Depletion  None  ...  None  None  None  None  None

[20 rows x 12 columns]