# add kw from OpenAlex to nodes_*.csv files
This adds keywords extracted from OpenAlex to the nodes_*.csv files created by biblionet.py

In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_json("/Users/poppyriddle/Documents/Github/IPCC_corpus/Corpus/labels/keywords_SDGs.json")
sdg_df = df[['sustainable_development_goals','keywords']]
sdg_df.iloc[0,0]
df

                                    id                                           keywords                      sustainable_development_goals
0     https://openalex.org/W2781567654  [{'id': 'https://openalex.org/keywords/marine-...  [{'display_name': 'Life below water', 'score':...
1     https://openalex.org/W2004113883  [{'id': 'https://openalex.org/keywords/futures...  [{'display_name': 'Climate action', 'id': 'htt...
2     https://openalex.org/W2013045877  [{'id': 'https://openalex.org/keywords/traditi...  [{'display_name': 'Quality education', 'id': '...
3     https://openalex.org/W2025956066  [{'id': 'https://openalex.org/keywords/cohesio...  [{'score': 0.85, 'display_name': 'Climate acti...
4     https://openalex.org/W4245300726  [{'id': 'https://openalex.org/keywords/terrige...  [{'score': 0.78, 'id': 'https://metadata.un.or...
...                                ...                                                ...                                                ...
6003  https://openalex.org/W4281790711                                                 []  [{'id': 'https://metadata.un.org/sdg/14', 'dis...
6004  https://openalex.org/W2590599124  [{'id': 'https://openalex.org/keywords/climate...  [{'score': 0.51, 'id': 'https://metadata.un.or...
6005  https://openalex.org/W3002986681  [{'id': 'https://openalex.org/keywords/storm-s...                                                 []
6006  https://openalex.org/W2955159091  [{'id': 'https://openalex.org/keywords/capacit...  [{'id': 'https://metadata.un.org/sdg/13', 'dis...
6007  https://openalex.org/W2587571975  [{'id': 'https://openalex.org/keywords/climate...  [{'display_name': 'Climate action', 'score': 0...

[6008 rows x 3 columns]

In [3]:
df2 = df['keywords'].apply(pd.Series)
df2

                                                     0                                                  1   ...   10   11
0     {'id': 'https://openalex.org/keywords/marine-e...  {'id': 'https://openalex.org/keywords/biogeoch...  ...  NaN  NaN
1     {'id': 'https://openalex.org/keywords/futures-...  {'id': 'https://openalex.org/keywords/risk-soc...  ...  NaN  NaN
2     {'id': 'https://openalex.org/keywords/traditio...                                                NaN  ...  NaN  NaN
3     {'id': 'https://openalex.org/keywords/cohesion...  {'id': 'https://openalex.org/keywords/cultural...  ...  NaN  NaN
4     {'id': 'https://openalex.org/keywords/terrigen...                                                NaN  ...  NaN  NaN
...                                                 ...                                                ...  ...  ...  ...
6003                                                NaN                                                NaN  ...  NaN  NaN
6004  {'id': 'https://openalex.org/keywords/climate-...                                                NaN  ...  NaN  NaN
6005  {'id': 'https://openalex.org/keywords/storm-su...  {'id': 'https://openalex.org/keywords/coastal-...  ...  NaN  NaN
6006  {'id': 'https://openalex.org/keywords/capacity...  {'id': 'https://openalex.org/keywords/adaptive...  ...  NaN  NaN
6007  {'id': 'https://openalex.org/keywords/climate-...  {'id': 'https://openalex.org/keywords/social-j...  ...  NaN  NaN

[6008 rows x 12 columns]

In [7]:
df2.fillna(inplace=True, value=0)

df3 = df2.map(lambda x: list(x.values()) if x!=0 else 0)
df4 = df3.map(lambda x: x[1] if x != 0 and len(x)>1 else None)
df4.head(20)
df4.to_excel("keywords2.xlsx")
df4.head(20)

OSError: [Errno 30] Read-only file system: 'keywords2.xlsx'