# DOI errors
This notebook fixes DOI errors
Checked for the following error types in a given list 
1. Included resolver (https://doi.org/, or http://doi.org/) at beginning or end of DOI 
2. Two DOIs concatenated together 
3. Forward slash encoded as ‘%2F’ 
4. Ending with period (.) 
5. Ending or starts with forward slash (/) 
6. Ending with space (and other characters after space) 
7. Ending with characters not part of DOI 
8. Contains NA or NF 
9. If unregistered in a RA 
10. Incomplete 
11. Badly formed prefix or suffix (missing or changed characters) 
12. Contains Crossref test account prefix
13. Duplicated DOIS within our dataset
14. Begins with 'doi:' or 'DOI:'

## UPDATED APRIL 10 2025
- [x] reran data.
- [x] cleaned up code.

In [25]:
import pandas as pd
from pandas import DataFrame, Series
import re # for regex
import os
import json # for import
import requests # send API calls
import time # enable pause for API calls
import numpy as np
from colorama import Fore,Style,Back,init # just for fun
from typing import List,Any

# set display options
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None) # show all columns
pd.set_option('display.max_colwidth', None)  # Show full content of each column

In [4]:
# import raw data

file = "IPCC_Report.txt"
df = pd.read_csv(file, sep='\t', encoding='utf-8', header=0,na_values=['NA','NA'])
print(df.columns)
#df

Index(['doi'], dtype='object')

In [5]:
# characterize df
# total rows
print(f"Total rows: {len(df)}")

# Count NaN values
nan_count = df['doi'].isna().sum()
print(f"Number of NaN values in 'doi' column: {nan_count}")

# percentage of filled values
df_non_nan = (df['doi'].notna().sum()/len(df))*100
print(Fore.YELLOW + f"Percent that are not NaN: {df_non_nan:.1f}")

# lengths of DOIs
doi_lengths = df['doi'].str.len().describe()
print(Fore.CYAN + f"\nDOI Lengths: \n{doi_lengths}")

#reset colors
print(Style.RESET_ALL)

Total rows: 6135
Number of NaN values in 'doi' column: 0
Percent that are not NaN: 100.0

DOI Lengths:
count    6135.000000
mean       23.652649
std         4.785057
min        13.000000
25%        20.000000
50%        24.000000
75%        27.000000
max        61.000000
Name: doi, dtype: float64

# #1 & #2: include resolver at beginning, end, or in middle of DOI
### how many rows start with 'https:' or 'http:'?

In [6]:
# count how many start with the resolver
count = df['doi'].str.startswith(('https://doi.org/','http://doi.org/')).sum()
print(f"Number of rows with http or https resolver: {count}")
percent = count/len(df)*100
print(f"percent with resolvers: {percent:.2f}%")

# Get rows with 'https:' with option for NaN value - passes a tuple for https or http
https_rows = df[df['doi'].str.startswith(('https:','http:'), na=False)]
print("\nRows starting with 'https:' or 'http':", len(https_rows))
percent = len(https_rows)/len(df)*100
print(f"Percentage of total: {percent:.2f}%")

print("\nThe first 5 examples:")
# Get just the 'doi' values that start with 'https:'
mask = (df['doi'].notna()) & (df['doi'].str.startswith(('https:','http:')))
https_rows = df[mask]['doi'].head(5)
print(https_rows)

Number of rows with http or https resolver: 1
percent with resolvers: 0.02%

Rows starting with 'https:' or 'http': 1
Percentage of total: 0.02%

The first 5 examples:
167    https://doi.org/10.2166/wp.2016.185
Name: doi, dtype: object

### now, let's remove https or http variants
This removes the resolver from anywhere in the string. When I checked a few manually, the removal of the resolver from the middle seems to create a valid DOI.

In [7]:
search_strings = ["https://doi.org/",
            "http://doi.org",
            "http://dx.doi.org/",
            
            ]
# remove https and http from the beginning - note the regex ^
# pattern = "^"+"|".join(search_strings)

# the following pattern just removes the search strings from anywhere in the 'doi'
pattern = "|".join(search_strings)
df['doi'] = df['doi'].str.replace(pattern, '', regex=True)

In [8]:
df['doi'].head(10)

0                     10.1002/rog.20022
1                   10.1038/nature19082
2                      10.1038/ngeo1787
3          10.1016/j.envdev.2018.12.003
4    10.1016/B978-0-12-407668-6.00010-0
5                  10.1038/Nclimate1666
6             10.1007/s10584-008-9520-z
7                       10.1002/wcc.297
8    10.1111/j.1467-7660.1995.tb00560.x
9             10.1080/10398560701701288
Name: doi, dtype: object

### Rows starting with 'https:' or 'http': 4675
### Percentage of total: 33.93%
All were corrected with removal.

# 3. Forward slash encoded as ‘%2F’ 
- [x] identify those with encoding for forward slash
- [x] manually check if replacing encoding with literal forward slash will create a resolving DOI
- [x] replace encoding with literal forward slash

In [9]:
print("Those with '%2F' as encoding:")
# Get just the 'doi' values that contain the encoding
mask = (df['doi'].notna()) & (df['doi'].str.contains(('%2F')))
encoded_rows = df[mask]['doi']
print(encoded_rows)
print(f"\nThose with encoded forward slashes: {len(encoded_rows)}")

Those with '%2F' as encoding:
Series([], Name: doi, dtype: object)

Those with encoded forward slashes: 0

In [39]:
# replace encoded '%2F' with literal forward slash
df['doi'] = df['doi'].str.replace("%2F", '/', regex=False)

# test those indices that came up before: 6624, 6815, 11130
#df.iloc[11130]

# #4: Contains period at end of DOI
- [x] check for period at end of DOI. This is often a mistake in copy and paste, however, it is a legitimate character permitted in a DOI. 
- [x] manually check for legit DOI before correcting
- [x] correct any that are not legit.

In [10]:
# check for period at end of DOI
print("Those with literal period at end of DOI:")
# Get just the 'doi' values that end with .
mask = (df['doi'].notna()) & (df['doi'].str.endswith(('.')))
period_ending_rows = df[mask]['doi']
print(period_ending_rows)
print(f"\nThose with literal periods at end of the DOI: {len(period_ending_rows)}")

Those with literal period at end of DOI:
Series([], Name: doi, dtype: object)

Those with literal periods at end of the DOI: 0

In [11]:
# check to see if these are legit
def check_doi(doi):
    url = "https://api.crossref.org/works/"
    try:
        response = requests.get(f"{url}/{doi}&mailto:pnriddle@dal.ca")
        if response.status_code == 404:
            return "Resource not found"
        elif response.status_code == 200:
            return "found"
        else:
            return f"status code: {response.status_code}"
    except Exception as e:
        return f"Error: {str(e)}"

#apply to df2
df2 = pd.DataFrame(columns = ['status'])
df2['status'] = period_ending_rows.apply(check_doi)

In [12]:
print(f"Those with periods at end AND were not found in Crossref: {(len(df2))}")
df2

Those with periods at end AND were not found in Crossref: 0

Empty DataFrame
Columns: [status]
Index: []

In [13]:
df['doi'] = df['doi'].str.rstrip(".")
# test on one of the indexes above
df.iloc[4224]

doi    10.1175/JPO-D-15-0056.1
Name: 4224, dtype: object

# # 5 & 6: Ending with forward slash (/) and Ending with space (and other characters after space) & 7 ending with chacters not part of the DOI. (partially)
- [x] identify those with endings
- [x] manually verify their legitimacy
- [x] run Crossref check
- [x] remove unwanted characters. 

### note
#7 is only partially complete. It will require manual checking of those that fail the registration check to see if there are obvious ones where characters, (such as error messages) have been concatenated onto a valid DOI.

In [14]:
# check for period at end of DOI
# Get just the 'doi' values that end with /
mask = (df['doi'].notna()) & (df['doi'].str.endswith(('/')) | df['doi'].str.startswith(('/')) )
slash_ending_rows = df[mask]['doi']
print(slash_ending_rows)
print(f"\nThose with literal slashes at beginning or end of the DOI: {len(slash_ending_rows)}")

print("\nThose ending with a space or containing a space in the DOI")
#get values that have or end with a space
mask = (df['doi'].notna()) & ((df['doi'].str.contains(' '))|(df['doi'].str.endswith(' ')))
contains_space = df[mask]['doi']
print(contains_space)
print(f"Those with containing or end with a space: {len(contains_space)}")

#how does it compare with those that end with a space

Series([], Name: doi, dtype: object)

Those with literal slashes at beginning or end of the DOI: 0

Those ending with a space or containing a space in the DOI
Series([], Name: doi, dtype: object)
Those with containing or end with a space: 0

In [15]:
# remove all / from 'doi' column
df['doi'] = df['doi'].apply(lambda x: x.lstrip('/') if isinstance(x,str) else x)

In [16]:
# these 9 need to be handled manually. I have created a list of tuples
# containing the index and the valid DOI value. 
tuple_list = [(657, "10.1136/bmjopen-2011-000152"),
                (1444, "10.33137/cjal-rcbu.v5.32938"),
                (1648, "10.7202/1021928ar"),
                (1649, "10.7202/1023786ar"),
                (1650, "10.7202/1030780ar"),
                (1651, "10.7202/1060828ar"),
                (4155, "10.7202/1033070"),
                (4331, "10.7202/1054201ar"),
                (8500, "10.1197/jamia.M1752")
                ]

for index, doi_value in tuple_list:
    df.at[index, 'doi'] = doi_value

In [48]:
# let's check those again:
df.iloc[657]['doi'] # yeah! that worked.

'10.1136/bmjopen-2011-000152'

# #8 Contains NA or NF
- [ ] check those that are Nan
- [ ] check strings that contain NA or NF
- [ ] be consistent, replace NA and NF with NaN

In [17]:
# Count NaN values
nan_count = df['doi'].isna().sum()
print(f"Number of NaN values in 'doi' column: {nan_count}")
print(Fore.CYAN + f"Percentage that are NaN values: {(nan_count/len(df))*100:.1f}")

# percentage of filled values
df_non_nan = (df['doi'].notna().sum()/len(df))*100
print(Fore.YELLOW + f"Percent that are not NaN: {df_non_nan:.1f}")

# count of those that contain 'NA' or 'NF'
mask = ((df['doi'].str.startswith('NA'))|(df['doi'].str.startswith('NF')))
contains_nanf = df[mask]['doi'].describe()
print(contains_nanf)

print(Style.RESET_ALL)

Number of NaN values in 'doi' column: 0
Percentage that are NaN values: 0.0
Percent that are not NaN: 100.0
count       0
unique      0
top       NaN
freq      NaN
Name: doi, dtype: object

In [98]:
# replace 'NF' with np.nan
df['doi'] = df['doi'].replace('NF', np.nan)

## #11: badly formed prefix or suffix

- [x] replace those with periods instead of forward slashes<br>
- [x] replace those with forward slash encoded as %2F

In [18]:
# how many DOIs are invalid in their structure?

# set up function to catch those with sequential dots
def filter_invalid_dois(df: pd.DataFrame, doi_column: str = 'doi') -> pd.Series:
    # Pattern matches DOIs with multiple sequential dots like 10.1.1.86.4340
    invalid_pattern: str = r'^10\.\d+\.\d+\.\d+'
    
    # Return DOIs that don't match this pattern
    return df[df[doi_column].str.contains(invalid_pattern, na=False)]['doi']

invalid_dois = filter_invalid_dois(df,'doi')
print(len(invalid_dois)) 
# just 5 of them, and only 2 seem legitimately bad
invalid_dois

0

Series([], Name: doi, dtype: object)

In [52]:
# overwrite index 3 and 5 with ''
df.loc[3, 'doi'] = np.nan
df.loc[5, 'doi'] = np.nan
# then rerun above and check the remainder for legitimacy.

# #12 Contain test prefixes
This checks for test prefixes

In [19]:
# check which DOIs are on a test prefix, such as 10.5555, 10.505050
# from API calls:
# https://api.crossref.org/members?query=test%20accounts
# https://api.crossref.org/members?query=Crossref

# removed 10.13003 and 10.18810

test_prefixes = ["10.5555",
                "10.88888",
                "10.30444",
                "10.30446",
                "10.30447",
                "10.30448",
                "10.30449",
                "10.50505",
                "10.30443"]

# check if prefixes are in 'doi'
# just playing with type annotation here
def get_strings_in_column(
    df: DataFrame,
    column: str,
    search_strings: List[str],
    case: bool = False,
    regex: bool = False) -> Series:
    pattern: str = '|'.join(search_strings)
    return df[df[column].str.contains(
        pattern,
        case=case,
        regex=regex,
        na=False
    )]

In [20]:

# If you want the entire DataFrame rows that match:
mask = df['doi'].str.contains('|'.join(test_prefixes),na=False)
matching_rows: DataFrame = df[mask]

print(Fore.MAGENTA + f"number of matching rows: {len(matching_rows)}")
print(Style.RESET_ALL)
matching_rows


# If you want just the matching values from the specified column:
#matching_values: Series = df[df['doi'].str.contains('|'.join(test_prefixes), na=False)]['doi']

number of matching rows: 0

Empty DataFrame
Columns: [doi]
Index: []

In [77]:
# so those will come back as invalid. I propose we overwrite them 
# and then search on their titles in Crossref or OpenAlex or manually search as there is only 7!
indexes_to_change = matching_rows.index

print(indexes_to_change)

Index([1553, 4996, 5049, 5058, 5219, 6225, 6487], dtype='int64')

In [132]:
# overwrite these indexes with None or valid doi
# Then use indexes to overwrite values
df.loc[mask,'doi'] = np.nan

# test to see if it worked
df.iloc[1553]

pub_id                                                      1771.0
title               Assessing the DVD Option in a Medical Library.
doc_type                                                   article
author_list_full                                        BD Cameron
publication_year                                            1998.0
source_name                                 Computers in libraries
volume                                                          18
issue                                                           10
pages                                                        60-64
bk_editor                                                      NaN
bk_edition                                                     NaN
publisher                                                      NaN
doi                                                            NaN
openalex_work_id                                               NaN
isbn                                                           NaN
url                                                            NaN
source_id                                                      NaN
Name: 1553, dtype: object

In [21]:
# Verify that no matching prefixes remain
mask_check = df['doi'].str.contains('|'.join(test_prefixes), na=False)
print(f"Check to see if any remain: {df[mask_check]}")

Check to see if any remain: Empty DataFrame
Columns: [doi]
Index: []

# #13 duplicate DOIs
- [x] identify duplicate DOIs rows
- [x] identify if title is the same or different

In [26]:
DataFrame = pd.DataFrame # set type annotation

# For DOIs and titles that are duplicated
doi_dupes = df[df['doi'].notna() & df['doi'].duplicated(keep=False)].sort_values('doi')
print(Fore.CYAN + f"Number of duplicates: {len(doi_dupes)}")
print(Style.RESET_ALL)
print("Duplicated DOIs with their indices:")
print(doi_dupes[['doi']].to_string())

# drop duplicates but keep first occurrence
df:DataFrame = df.drop_duplicates(subset=['doi'], keep='first')
doi_dupes_deduped:DataFrame = doi_dupes.drop_duplicates(subset=['doi'], keep='first')

print(f"new length of df: {len(df)}")
print(f"number of DOIs that had duplicates: {len(doi_dupes_deduped)}")
print(f"this process removed: {len(doi_dupes)-len(doi_dupes_deduped)}")

Number of duplicates: 484

Duplicated DOIs with their indices:
                                        doi
1479                   10.1002/2013GL059010
2980                   10.1002/2013GL059010
2083                   10.1002/2013GL059069
3404                   10.1002/2013GL059069
3683                   10.1002/2014EF000272
6006                   10.1002/2014EF000272
2272                   10.1002/2014GL060140
3549                   10.1002/2014GL060140
4481                   10.1002/2014JC010470
1701                   10.1002/2014JC010470
666                    10.1002/2015GB005237
1664                   10.1002/2015GB005237
1254                   10.1002/2015GL063846
3983                   10.1002/2015GL063846
4323                   10.1002/2015gb005338
5571                   10.1002/2015gb005338
6057                   10.1002/2016EF000505
3761                   10.1002/2016EF000505
3396                   10.1002/2016GL067695
2078                   10.1002/2016GL067695
5111                   10.1002/2016GL067757
5968                   10.1002/2016GL067757
2510                   10.1002/2016GL068977
333                    10.1002/2016GL068977
4764                   10.1002/2016GL070023
5782                   10.1002/2016GL070023
2431                   10.1002/2016GL070414
3665                   10.1002/2016GL070414
2200                   10.1002/2016GL071489
4940                   10.1002/2016GL071489
5344                   10.1002/2016GL071668
6104                   10.1002/2016GL071668
3976                   10.1002/2017EF000589
2756                   10.1002/2017EF000589
5018                   10.1002/2017GL074837
2277                   10.1002/2017GL074837
3398                   10.1002/2017GL074954
2079                   10.1002/2017GL074954
5138                   10.1002/2017GL076350
5984                   10.1002/2017GL076350
1056                   10.1002/2017JD026592
6024                   10.1002/2017JD026592
1433                      10.1002/ece3.1357
4195                      10.1002/ece3.1357
1685                      10.1002/ecs2.1213
4470                      10.1002/ecs2.1213
2650                       10.1002/ecy.1749
5354                       10.1002/ecy.1749
1449                       10.1002/ppp.1919
537                        10.1002/ppp.1919
3863                      10.1002/rog.20022
0                         10.1002/rog.20022
1697                      10.1002/wat2.1016
681                       10.1002/wat2.1016
212             10.1007/978-3-030-05252-2_1
3325            10.1007/978-3-030-05252-2_1
4210            10.1007/978-981-13-2306-5_1
4209            10.1007/978-981-13-2306-5_1
3994              10.1007/s00267-013-0132-7
31                10.1007/s00267-013-0132-7
2768              10.1007/s10113-016-1044-x
3991              10.1007/s10113-016-1044-x
3391              10.1007/s10113-018-1360-4
4814              10.1007/s10113-018-1360-4
688               10.1007/s10113-018-1385-8
159               10.1007/s10113-018-1385-8
5648              10.1007/s10113-018-1385-8
4696              10.1007/s10584-015-1376-4
5753              10.1007/s10584-015-1376-4
5779              10.1007/s10584-018-2205-3
2015              10.1007/s10584-018-2205-3
3784              10.1007/s12237-016-0166-1
5299              10.1007/s12237-016-0166-1
224               10.1007/s12571-018-0827-y
840               10.1007/s12571-018-0827-y
274               10.1016/j.crm.2017.06.005
4976              10.1016/j.crm.2017.06.005
4930              10.1016/j.csr.2017.02.004
5890              10.1016/j.csr.2017.02.004
2944         10.1016/j.ecolecon.2015.12.006
4214         10.1016/j.ecolecon.2015.12.006
2359           10.1016/j.envpol.2015.08.012
1001           10.1016/j.envpol.2015.08.012
106            10.1016/j.envsci.2017.10.012
1515           10.1016/j.envsci.2017.10.012
195            10.1016/j.envsci.2018.01.012
5719           10.1016/j.envsci.2018.01.012
4731           10.1016/j.envsci.2018.09.002
3319           10.1016/j.envsci.2018.09.002
2618             10.1016/j.epsl.2018.08.049
1097             10.1016/j.epsl.2018.08.049
4468          10.1016/j.fishres.2014.09.010
4469          10.1016/j.fishres.2014.09.010
1188        10.1016/j.gloenvcha.2011.04.006
13          10.1016/j.gloenvcha.2011.04.006
5771        10.1016/j.gloenvcha.2011.09.016
2000        10.1016/j.gloenvcha.2011.09.016
136         10.1016/j.gloenvcha.2012.12.006
3080        10.1016/j.gloenvcha.2012.12.006
188         10.1016/j.gloplacha.2015.02.008
1850        10.1016/j.gloplacha.2015.02.008
4789        10.1016/j.gloplacha.2016.08.009
223         10.1016/j.gloplacha.2016.08.009
1380        10.1016/j.gloplacha.2017.11.017
501         10.1016/j.gloplacha.2017.11.017
5632            10.1016/j.ijdrr.2014.07.007
4472            10.1016/j.ijdrr.2014.07.007
5394            10.1016/j.ijsbe.2017.03.007
3930            10.1016/j.ijsbe.2017.03.007
117           10.1016/j.jenvman.2015.11.011
5578          10.1016/j.jenvman.2015.11.011
1285          10.1016/j.jmarsys.2008.11.022
4014          10.1016/j.jmarsys.2008.11.022
1325           10.1016/j.marpol.2016.09.001
4065           10.1016/j.marpol.2016.09.001
4387           10.1016/j.marpol.2017.06.012
4386           10.1016/j.marpol.2017.06.012
1422           10.1016/j.marpol.2017.09.011
75             10.1016/j.marpol.2017.09.011
4432           10.1016/j.marpol.2019.02.004
5610           10.1016/j.marpol.2019.02.004
5286        10.1016/j.ocecoaman.2014.03.009
3776        10.1016/j.ocecoaman.2014.03.009
2958        10.1016/j.ocecoaman.2015.02.008
4251        10.1016/j.ocecoaman.2015.02.008
1736           10.1016/j.pocean.2016.10.004
4501           10.1016/j.pocean.2016.10.004
2956        10.1016/j.scitotenv.2018.06.006
4244        10.1016/j.scitotenv.2018.06.006
662            10.1017/CBO9781107415324.008
5611           10.1017/CBO9781107415324.008
5917           10.1017/CBO9781107415324.010
4999           10.1017/CBO9781107415324.010
280            10.1017/CBO9781107415324.010
214            10.1017/CBO9781107415324.013
5777           10.1017/CBO9781107415324.013
104            10.1017/CBO9781107415324.020
4298           10.1017/CBO9781107415324.020
5560           10.1017/CBO9781107415324.020
32             10.1017/CBO9781107415324.022
3995           10.1017/CBO9781107415324.022
2777           10.1017/CBO9781107415324.022
5425           10.1017/CBO9781107415324.022
429            10.1017/CBO9781107415324.022
5493           10.1017/CBO9781107415324.024
4147           10.1017/CBO9781107415324.024
63             10.1017/CBO9781107415324.024
60             10.1017/CBO9781107415324.026
5481           10.1017/CBO9781107415324.026
16                10.1017/S2047102515000151
1224              10.1017/S2047102515000151
4079                   10.1029/2011JC007409
1331                   10.1029/2011JC007409
4439                   10.1029/2011gl050087
1668                   10.1029/2011gl050087
996                    10.1029/2017JF004358
2351                   10.1029/2017JF004358
173                    10.1029/2017JG004248
1800                   10.1029/2017JG004248
2145                    10.1038/nature04095
4876                    10.1038/nature04095
4821                    10.1038/nature12540
232                     10.1038/nature12540
5703                    10.1038/nature13278
3238                    10.1038/nature13278
2338                    10.1038/nature14338
988                     10.1038/nature14338
4779                    10.1038/nature16156
2034                    10.1038/nature16156
1425                    10.1038/nature17145
2925                    10.1038/nature17145
1169                    10.1038/nature17447
2696                    10.1038/nature17447
326                     10.1038/nature21058
5193                    10.1038/nature21058
5517                    10.1038/nature21068
1435                    10.1038/nature21068
3805                    10.1038/nature24458
2622                    10.1038/nature24458
5472                   10.1038/nclimate1854
2857                   10.1038/nclimate1854
2999                   10.1038/nclimate2094
1495                   10.1038/nclimate2094
5788                   10.1038/nclimate2330
3352                   10.1038/nclimate2330
5036                   10.1038/nclimate2513
2283                   10.1038/nclimate2513
6035                   10.1038/nclimate2657
337                    10.1038/nclimate2657
1662                   10.1038/nclimate2844
4437                   10.1038/nclimate2844
286                    10.1038/nclimate2872
5019                   10.1038/nclimate2872
353                    10.1038/nclimate2876
3757                   10.1038/nclimate2876
3031                   10.1038/nclimate2912
1559                   10.1038/nclimate2912
107                    10.1038/nclimate2954
1525                   10.1038/nclimate2954
4549                   10.1038/nclimate3103
170                    10.1038/nclimate3103
1785                   10.1038/nclimate3103
3407                    10.1038/ncomms11969
5828                    10.1038/ncomms11969
3445                    10.1038/ncomms14730
880                     10.1038/ncomms14730
2121                    10.1038/ncomms14730
3156                     10.1038/ncomms8188
5645                     10.1038/ncomms8188
1286                     10.1038/ncomms9220
4015                     10.1038/ncomms9220
1164                       10.1038/ngeo1787
2                          10.1038/ngeo1787
2357                       10.1038/ngeo2007
304                        10.1038/ngeo2007
682                        10.1038/ngeo2331
1712                       10.1038/ngeo2331
5798                       10.1038/ngeo2792
3364                       10.1038/ngeo2792
5487             10.1038/s41467-018-02992-9
1376             10.1038/s41467-018-02992-9
3571             10.1038/s41467-018-03353-2
2299             10.1038/s41467-018-03353-2
3972             10.1038/s41467-018-04568-z
5412             10.1038/s41467-018-04568-z
5797             10.1038/s41467-018-07865-9
2038             10.1038/s41467-018-07865-9
4341              10.1038/s41558-017-0022-8
1569              10.1038/s41558-017-0022-8
1881              10.1038/s41558-017-0054-0
4627              10.1038/s41558-017-0054-0
4640              10.1038/s41558-017-0057-x
1901              10.1038/s41558-017-0057-x
1405              10.1038/s41558-018-0092-2
70                10.1038/s41558-018-0092-2
510               10.1038/s41558-018-0092-2
6132              10.1038/s41558-018-0156-3
371               10.1038/s41558-018-0156-3
1010              10.1038/s41558-018-0296-5
2382              10.1038/s41558-018-0296-5
1002              10.1038/s41558-018-0393-5
2360              10.1038/s41558-018-0393-5
252               10.1038/s41561-018-0152-2
4878              10.1038/s41561-018-0152-2
2992              10.1038/s41561-019-0300-3
569               10.1038/s41561-019-0300-3
6027              10.1038/s41586-018-0007-4
5220              10.1038/s41586-018-0007-4
2509              10.1038/s41586-018-0007-4
2501              10.1038/s41586-018-0179-y
3704              10.1038/s41586-018-0179-y
1942              10.1038/s41586-018-0371-0
203               10.1038/s41586-018-0371-0
2801              10.1038/s41586-018-0712-z
1306              10.1038/s41586-018-0712-z
6038              10.1038/s41586-018-0752-4
2522              10.1038/s41586-018-0752-4
339               10.1038/s41586-018-0752-4
3721              10.1038/s41586-018-0752-4
1473              10.1038/s41586-019-0901-4
2967              10.1038/s41586-019-0901-4
1137              10.1038/s41586-019-1071-0
3847              10.1038/s41586-019-1071-0
2659              10.1038/s41586-019-1071-0
3755             10.1038/s41598-017-01362-7
6054             10.1038/s41598-017-01362-7
5622                      10.1038/srep38402
4460                      10.1038/srep38402
5768                      10.1038/srep45242
1996                      10.1038/srep45242
295                       10.1063/1.1510279
5083                      10.1063/1.1510279
2519                10.1073/pnas.1016560108
5240                10.1073/pnas.1016560108
5679                10.1073/pnas.1115521109
1805                10.1073/pnas.1115521109
1305                10.1073/pnas.1210508110
5441                10.1073/pnas.1210508110
4471                10.1073/pnas.1222469111
151                 10.1073/pnas.1222469111
2976                10.1073/pnas.1301293110
5537                10.1073/pnas.1301293110
1299                10.1073/pnas.1611707114
4037                10.1073/pnas.1611707114
4372                10.1073/pnas.1619575114
127                 10.1073/pnas.1619575114
2025                10.1073/pnas.1719903115
218                 10.1073/pnas.1719903115
2273                10.1073/pnas.1812883116
3550                10.1073/pnas.1812883116
380               10.1080/10398560701701288
9                 10.1080/10398560701701288
35            10.1080/14494035.2018.1513731
5428          10.1080/14494035.2018.1513731
368           10.1080/2154896X.2016.1253823
2648          10.1080/2154896X.2016.1253823
886           10.1080/24694452.2016.1235495
244           10.1080/24694452.2016.1235495
1541          10.1088/1748-9326/10/1/014005
5563          10.1088/1748-9326/10/1/014005
1876               10.1088/1748-9326/aad624
5711               10.1088/1748-9326/aad624
1670                 10.1093/icesjms/fss021
4442                 10.1093/icesjms/fss021
1221                 10.1093/icesjms/fsw066
3942                 10.1093/icesjms/fsw066
2223                 10.1098/rsta.2014.0160
5901                 10.1098/rsta.2014.0160
273                 10.1111/1365-2664.12550
2237                10.1111/1365-2664.12550
367                      10.1111/area.12189
6107                     10.1111/area.12189
1893                     10.1111/cobi.12474
4635                     10.1111/cobi.12474
1162                      10.1111/ele.12871
3864                      10.1111/ele.12871
1126                      10.1111/eva.12613
2645                      10.1111/eva.12613
4476                      10.1111/fog.12083
5635                      10.1111/fog.12083
4151                      10.1111/gcb.12623
1388                      10.1111/gcb.12623
4961                      10.1111/gcb.12833
270                       10.1111/gcb.12833
3858                      10.1111/gcb.13538
1157                      10.1111/gcb.13538
5259                      10.1111/gcb.13647
5260                      10.1111/gcb.13647
1278                      10.1111/gcb.13712
3996                      10.1111/gcb.13712
4457                      10.1111/gcb.13768
3128                      10.1111/gcb.13768
2052                 10.1126/sciadv.1601426
4787                 10.1126/sciadv.1601426
4118                 10.1126/sciadv.1601545
1353                 10.1126/sciadv.1601545
2855                 10.1126/sciadv.1601545
5470                 10.1126/sciadv.1601545
3572                 10.1126/sciadv.aav3738
2300                 10.1126/sciadv.aav3738
3622                10.1126/science.1228102
2361                10.1126/science.1228102
1571                10.1126/science.1234532
605                 10.1126/science.1234532
2217                10.1126/science.1235225
5897                10.1126/science.1235225
5377                10.1126/science.1248222
2693                10.1126/science.1248222
1787                10.1126/science.1249055
3190                10.1126/science.1249055
1902                10.1126/science.aab2620
5718                10.1126/science.aab2620
4350                10.1126/science.aac4722
120                 10.1126/science.aac4722
5191                10.1126/science.aac9874
2475                10.1126/science.aac9874
5308                10.1126/science.aad8745
6086                10.1126/science.aad8745
2184                10.1126/science.aai9214
4910                10.1126/science.aai9214
913                 10.1126/science.aai9214
160                 10.1126/science.aan8048
5649                10.1126/science.aan8048
4495                10.1126/science.aan8048
1232                10.1126/science.aao1447
2743                10.1126/science.aao1447
2282                10.1126/science.aat7850
5930                10.1126/science.aat7850
4398                10.1126/science.aau5153
1622                10.1126/science.aau5153
133                 10.1126/science.aau5153
805                    10.1139/er-2017-0032
1993                   10.1139/er-2017-0032
2372                       10.1144/SP461.15
2373                       10.1144/SP461.15
1270  10.1146/annurev-environ-051211-123836
30    10.1146/annurev-environ-051211-123836
5198   10.1146/annurev-marine-052915-100829
2478   10.1146/annurev-marine-052915-100829
328    10.1146/annurev-marine-052915-100829
5671   10.1146/annurev-marine-121916-063102
4556   10.1146/annurev-marine-121916-063102
5707    10.1175/2016BAMSStateoftheClimate.1
5520    10.1175/2016BAMSStateoftheClimate.1
6012    10.1175/2018BAMSStateoftheClimate.1
5533    10.1175/2018BAMSStateoftheClimate.1
330               10.1175/BAMS-D-11-00094.1
1049              10.1175/BAMS-D-11-00094.1
5601              10.1175/BAMS-D-13-00085.1
5504              10.1175/BAMS-D-13-00085.1
6007              10.1175/BAMS-D-13-00085.1
6122              10.1175/BAMS-D-13-00085.1
2385              10.1175/JCLI-D-12-00341.1
1013              10.1175/JCLI-D-12-00341.1
2234              10.1175/JCLI-D-12-00834.1
4963              10.1175/JCLI-D-12-00834.1
5406              10.1175/JCLI-D-14-00589.1
1235              10.1175/JCLI-D-14-00589.1
3224               10.1175/JCLI-D-15-0129.1
5693               10.1175/JCLI-D-15-0129.1
3365               10.1175/JCLI-D-15-0153.1
4785               10.1175/JCLI-D-15-0153.1
5706               10.1175/JCLI-D-15-0654.1
1867               10.1175/JCLI-D-15-0654.1
1431               10.1175/JCLI-D-16-0396.1
4192               10.1175/JCLI-D-16-0396.1
6099               10.1175/JCLI-D-17-0068.1
3825               10.1175/JCLI-D-17-0068.1
51                 10.1175/JCLI-D-18-0149.1
4093               10.1175/JCLI-D-18-0149.1
4448                     10.1175/JCLI3990.1
670                      10.1175/JCLI3990.1
5572              10.1175/jcli-d-14-00117.1
4324              10.1175/jcli-d-14-00117.1
5129               10.1175/jcli-d-18-0170.1
2363               10.1175/jcli-d-18-0170.1
5594               10.1177/0309133317751843
4379               10.1177/0309133317751843
366    10.12987/yale/9780300198812.003.0007
1113   10.12987/yale/9780300198812.003.0007
4649           10.1371/journal.pone.0073748
3260           10.1371/journal.pone.0073748
2178                    10.14430/arctic4475
5874                    10.14430/arctic4475
191                    10.14512/gaia.28.2.5
760                    10.14512/gaia.28.2.5
167                     10.2166/wp.2016.185
713                     10.2166/wp.2016.185
262             10.3112/erdkunde.2015.01.05
910             10.3112/erdkunde.2015.01.05
3317                  10.3189/2013AoG63A256
1980                  10.3189/2013AoG63A256
4571                      10.3354/meps11189
1807                      10.3354/meps11189
1514                      10.3354/meps11982
4303                      10.3354/meps11982
2312                      10.3354/meps12278
5078                      10.3354/meps12278
1104               10.3389/feart.2019.00096
2627               10.3389/feart.2019.00096
1463                10.3389/fevo.2014.00068
4241                10.3389/fevo.2014.00068
2462               10.3389/fmars.2016.00028
5184               10.3389/fmars.2016.00028
5872               10.3389/fmars.2017.00289
4906               10.3389/fmars.2017.00289
4351               10.3389/fmars.2018.00337
121                10.3389/fmars.2018.00337
4781                   10.3897/BDJ.5.e11764
3359                   10.3897/BDJ.5.e11764
1914                    10.4000/emscat.3280
194                     10.4000/emscat.3280

# #14 those starting with DOI: or doi:
- [x] identify how many start with 'DOI:' or 'doi:'
- [x] remove them using lstrip or replace

In [31]:
# identify how many start with 'DOI:' or 'doi:'

search_strings = ["DOI:","doi:"]
# remove https and http from the beginning - note the regex ^
pattern = "^"+"|".join(search_strings)
# the following pattern just removes the search strings from anywhere in the 'doi'
#pattern = "|".join(search_strings)

mask = df['doi'].str.contains(pattern,regex=True, na=False)
print(Fore.MAGENTA + f"How many DOIs contain 'DOI:' or 'doi:': {len(df[mask])}") 
print(Style.RESET_ALL)

How many DOIs contain 'DOI:' or 'doi:': 0

In [205]:
# remove those that match the pattern in the above cell:
df['doi'] = df['doi'].str.replace(pattern, '', regex=True)

# #9: check if DOI is valid/registered
- [ ] run through agency check
- [ ] run through each agencies validity check

In [27]:
from tqdm import tqdm
tqdm.pandas()

# check agency function
def agency_check(doi):
    """
    This function takes a DOI and passes it to a Crossref REST API call
    that checks which agency the DOI, if valid, is registered to. 
    Returns: Resource not found
            the agency label
            error code
    """
    url = "https://api.crossref.org/works/"
    try:
        response = requests.get(f"{url}{doi}/agency")
        if response.status_code == 404:
            return "Resource not found"
            print("Resource not found")
        elif response.status_code == 200:
            data = response.json()
            agency_id = data['message']['agency']['label']
            return agency_id
            print(agency_id)
        else:
            return f"Status code: {response.status_code}"
            print(f"error: {response.status_code}")
    except Exception as e:
        return f"There's some sort of error: {str(e)}"



def crossref_check_doi(doi):
    """
    This function takes a DOI and passes it to a Crossref REST API call
    returns: Resource not found
            ok status code to indicate it is registered and a valid DOI
            an error message
    """
    url = "https://api.crossref.org/works/"
    try:
        response = requests.get(f"{url}{doi}")
        if response.status_code == 404:
            return "Resource not found"
        elif response.status_code == 200:
            data = response.json()
            status_msg = data['status']
            return status_msg
        else:
            return f"status code: {response.status_code}"
    except Exception as e:
        return f"Error: {str(e)}"

In [28]:
doi = "10.4242/BalisageVol8.Huitfeldt02"
agency_check(doi)

'Crossref'

In [29]:
#df2 = pd.DataFrame(columns=['registration_agency'])
# check which agency they are on#=
# df2['registration agency'] = df['doi'].apply(agency_check)

# If applying to a DataFrame column
# df2['agency'] = [agency_check(doi) for doi in tqdm(df['doi'], desc="Checking DOIs")]

# OR if applying using apply()
df['registration_agency'] = [agency_check(doi) if pd.notna(doi) else None 
                for doi in tqdm(df['doi'], desc="Checking agency for DOIs")]

Checking agency for DOIs: 100%|██████████| 5883/5883 [23:30<00:00,  4.17it/s]

In [30]:
print(df.columns)
df['registration_agency'].value_counts()

Index(['doi', 'registration_agency'], dtype='object')

registration_agency
Crossref              5845
Resource not found      29
DataCite                 7
ISTIC                    2
Name: count, dtype: int64

All DOIs and their DOI registration status:<br>
|registration_agency| Count |
| ----------------- | ------|
|Crossref           |   9813|
|DataCite           |    280|
|Resource not found |    110|
|mEDRA              |      7|
|CNKI               |      1|
|ISTIC              |      1|
|KISTI              |      1|
<br>
Any with resource not found should be flagged for follow up with Crossref, title match with OpenAlex or OpenAire<br>

# # 10 Incomplete
Will need to manually check those that returned from #9 to see if incompleteness can be solved? May need to be a title and author match

In [32]:
df_incomplete = df[['doi','registration_agency']]
df_incomplete = df_incomplete.query("registration_agency == 'Resource not found'")
df_incomplete

                                                                doi registration_agency
108                                        10.1038/s41558-0190435-7  Resource not found
113                                            10.5194/tc-7375-2013  Resource not found
162                 10.1890/1051-0761(2000)010[1270:UTEKIS]2.0.CO;2  Resource not found
166                 10.1175/1520-0442(1999)012<2169:TDROTG>2.0.CO;2  Resource not found
178                                          10.5194/bg-113647-2014  Resource not found
261                 10.1175/1520-0477(2000)081<0443:IOEWAC>2.3.CO;2  Resource not found
424                    10.1659/0276-4741(2006)26[304:SMTAT]2.0.CO;2  Resource not found
883                 10.1659/0276-4741(2004)024[0024:NHATNF]2.0.CO;2  Resource not found
1017  10.1002/(SICI)1099-1530(199610)7:4<301::AID-PPP231>3.0.CO;2-R  Resource not found
1228                                  10.1088/1748-9326/aac2f0/meta  Resource not found
1291                                        10.1088/17489326/aaf2ed  Resource not found
1337                10.1175/1520-0493(1980)108<2032:MOOTWP>2.0.CO;2  Resource not found
1580                  10.1579/0044-7447(2006)35[203:INTSAC]2.0.CO;2  Resource not found
1773                10.1890/1051-0761(2000)010[0423:TVDOSO]2.0.CO;2  Resource not found
2155                                       10.1007/s00300-0151760-6  Resource not found
2264                10.1175/1520-0442(2002)015<1609:AIISAS>2.0.CO;2  Resource not found
2472                                       10.1038/s41561018-0226-1  Resource not found
2588                10.1175/1520-0442(1999)012<1814:SDOASI>2.0.CO;2  Resource not found
2642                10.1175/1525-7541(2004)005<0595:DCACOT>2.0.CO;2  Resource not found
3064                                       10.1038/s41586019-0889-9  Resource not found
3107                10.1672/0277-5212(2002)022[0071:AACCIO]2.0.CO;2  Resource not found
3392                                  10.1088/17489326/10/10/104004  Resource not found
4072                                       10.1038/s41586018-0006-5  Resource not found
4155                                                10.7202/1033070  Resource not found
4405                10.1890/1540-9295(2006)004[0141:WHCISC]2.0.CO;2  Resource not found
4572                10.1175/1520-0485(1987)017<2294:EODOCD>2.0.CO;2  Resource not found
4877                  10.1641/0006-3568(2006)56[987:AGCFSE]2.0.CO;2  Resource not found
5495                  10.1579/0044-7447(2008)37[241:TVOCWF]2.0.CO;2  Resource not found
5903                                       10.15294/usej.v7i1.19536  Resource not found

In [33]:
### IT IS NOT NECESSARY TO RUN THIS CODE ###

results = []
for doi in tqdm(df['doi'], desc="Checking Crossref for DOIs"):
    if pd.notna(doi):
        check_result = crossref_check_doi(doi)
        results.append({'doi': doi, 'crossref_registration_check': check_result})
    else:
        results.append({'doi': None, 'crossref_registration_check': None})
df2 = pd.DataFrame(results)

#then join df2 to df on doi
print(f"length of df2: {len(df2)}")
print(f"length of df: {len(df)}")

Checking Crossref for DOIs: 100%|██████████| 5883/5883 [22:05<00:00,  4.44it/s]

In [38]:
# check those that are resource not found and don't belong to Crossref
print(Fore.CYAN + "DOIS and their registration agencies after cleaning:")
print("These numbers may change as publishers register or transfer DOIs.")
print(Fore.YELLOW + f"{df['registration_agency'].value_counts()}")

print(df3.dtypes)

print(Style.RESET_ALL)

DOIS and their registration agencies after cleaning:
These numbers may change as publishers register or transfer DOIs.
registration_agency
Crossref              5845
Resource not found      29
DataCite                 7
ISTIC                    2
Name: count, dtype: int64
doi                            object
registration_agency            object
crossref_registration_check    object
dtype: object

In [37]:
#export as .txt
file_to_be_saved = "IPCC_Report_cleaned_DOIs.txt"
df.to_csv(file_to_be_saved, sep='\t', encoding='utf-8',na_rep='NA')

All DOIs and their DOI registration status:<br>
|registration_agency| Count |
| ----------------- | ------|
|Crossref           |   9813|
|DataCite           |    280|
|Resource not found |    110|
|mEDRA              |      7|
|CNKI               |      1|
|ISTIC              |      1|
|KISTI              |      1|
<br>
Any with resource not found should be flagged for follow up with Crossref, title match with OpenAlex or OpenAire<br>